
## Tutorial tentativo:

### 1. Directorio de trabajo

Lo primero que debe hacer es elegir el directorio de trabajo en el que va a trabajar. Para el curso recomendamos crear una carpeta llamada "CursoR", aunque puede llamarse como usted quiera. Si aún no la creó puede crearla directamente con R, con el comando:

    dir.create("CursoR")

Escriba o copie y pegue esto en la consola de R que se encuentra en RStudio (panel de abajo-izquierda, o izquierda simplemente; bajo el nombre de "Console"). De enter. Esto va a crear una carpeta llamada CursoR dentro del directorio de trabajo actual. Puede confirmar de dos formas que la carpeta efectivamente fue creada: 1. con el navegador de archivos normal de su sistema operativo o 2. con el comando `dir`:

    dir()

Escribiendo esto en la consola (y dando enter) vemos una lista de nombres de achivos y carpetas. Allí se debería incluir "CursoR" si hicimos todo bien hasta el momento.

Como recordará de la lección 1.4, usted puede saber cuál es la carpeta de trabajo actual con la función `getwd`. De todas formas lo que nos interesa es "ubicarnos" en la carpeta CursoR, así que vamos a usar `setwd` para hacerlo:

    setwd("CursoR")

Nótese que aquí usamos el camino relativo para ubicarnos. Es útil de momento, pero no siempre es lo ideal.

Podríamos haber hecho lo mismo con los botones de RStudio: ``Session >> Set Working Directory >> Choose Directory`` (o la combinación de teclas Ctrl + Shift + k). Nótese que el comando `setwd("camino absoluto")` aparece igualmente en la consola (abajo-izquierda) y además también aparece en la historia de comandos. Dicha historia se encuentra en el panel de arriba-derecha, en la pestaña "History". Esta historia es muy útil si queremos buscar y recuperar algún comando ejecutado hace un tiempo (aunque no es infinita).

### 2. El command prompt

Nuestro primer comando (no escribir aún), será este:

    mi.objeto <- 4

Pero, ¿dónde vamos a escribirlo? 

- Opción 1: la consola de RStudio. Sólo hay que dar enter al terminar de escribirlo. No hace falta que el cursor esté al final de la sentencia para dar el enter.

- Opción 2: en el editor de texto plano de RStudio (arriba-izquierda). Primero debe iniciar un archivo nuevo: vaya a ``File >> New >> R Script`` (Ctrl + Shift + N), recién entonces será visible este panel. En RStudio este panel se llama "Source" (en inglés, fuente); es el "código fuente" con el que trabajamos en un momento dado. Como aún no guardamos el archivo, este figura bajo el nombre "Untitled1" (Sin título 1).
    
En general preferimos la segunda opción. Escribir los comandos en el editor nos permite guardar todo lo que hacemos, de forma que se puede repetir en el futuro con facilidad.

A continuación, escriba nuestro comando, primero en la consola, dando enter al final para que se ejecute, y luego en el Source (editor de texto):

    mi.objeto <- 4

Nota: ponga los espacios en blanco también; no afectan al comando, pero facilitan la lectura.

Debido a que usted le dió enter al comando en la consola, ahora en su sesión existe un objeto llamado `mi.objeto`. Puede ver una lista de los objetos que existen en el panel de arriba-derecha, bajo la pestaña "Workspace" (área de trabajo). 
También puede ver una lista de objetos existentes con el comando `ls`: escriba en la consola

    ls()

Ahora veamos como terminar de usar la "opción 2". Como se dijo antes, preferimos usar el editor para escribir nuestros comandos, ya que nos permite repetirlos fácilmente. En RStudio se pueden ejecutar directamente los comandos escritos en el editor de texto plano. Hay que ubicar al cursor en la línea que nos interesa y apretar las teclas Ctrl + Enter (en simultáneo). Haga la prueba con la línea `mi.objeto <- 4`.

Al usar Ctrl + Enter podemos ver que aparece la misma línea en la consola y se ve así:

    > mi.objeto <- 4
    >

Al ver esto tenemos la información necesaria para saber que el comando ya fue ejecutado, ¿cómo? gracias a la existencia del "command prompt", el signo de `>` que aparece al principio de cada línea en la consola.

El command prompt solo que aparece en la última línea es un indicador de que R ya terminó de ejecutar todo lo que se le pidió anteriormente. Es una forma de decir "estoy listo para recibir órdenes". Considere ahora las diferencias entre encontrar esto en la consola:

    > mi.objeto <- 4

y esto:

    > mi.objeto <- 4
    >

En el primer caso el comando `mi.objeto <- 4` aún no se ejecutó, mientras que en el segundo sí. ¿Ve la diferencia?

Un error de principiante muy común es el de copiar líneas de comando incluyendo el/los command prompt al principio. Al tratar de ejecutar estas líneas surge un error que difícilmente pueda comprender el usuario, ya que suele ser un principiante. Es buena idea ver un ejemplo de este error: en el editor, agregue un command propt al principio de nuestro comando, de forma que quede así: "`> mi.objeto <- 4`" (sin las comillas). Ahora envíe esta línea a la consola (ponga el cursor en esa línea y aprete Ctrl + Enter). Vea el mensaje de error que devuelve R:

    > > mi.objeto <- 4
    Error: unexpected '>' in ">"

Nota: puede que el mensaje esté en español en su PC, dependiendo del idioma en el que haya instalado R. Borre el command prompt que acaba de agregar para evitar errores futuros.

El command prompt es entonces una indicación útil, pero también molesta. Muchas veces en libros o páginas web se muestran comandos de R que empiezan con el command prompt, lo cual es muy desconsiderado, ya que el usuario debe encargarse de borrar manualmente cada uno antes de poder reproducir los ejemplos.

El command prompt tiene otra variante, el signo de `+`. El significado es diferente, indica que los comandos anteriores no están completos. Por ejemplo, si escribo `mi.objeto <-` va a faltar algo. Haga el ejemplo vaya al editor y borre el 4 al final de nuestro comando, luego envíelo a la consola de R. Puede ver que en la misma aparece lo siguiente:

    > mi.objeto <-
    +

Esta es la forma de R de indicar que el comando no está completo. Le está diciendo al usuario "aún me falta algo para poder ejecutar sus órdenes, dígame ¿qué valor debo asignar a `mi.objeto`?". El usuario, usted, puede completar el comando sin problemas: vaya a la consola y escriba 4. Ahora de enter. Debería ver esto:

    > mi.objeto <-
    + 4
    >

También tiene la opción de interrumpir el comando y volver al command prompt normal. Alcanza con ir a la consola y apretar la tecla de escape (Esc). En este caso se ve así en la consola:

    > mi.objeto <-
    + 

    >

Pasaremos ahora a hacer cosas más elaboradas ...

Si no lo hizo antes, agregue al principio del script el comando que sirve para elegir el directorio de trabajo. Si usted usó los botones de RStudio (o la combinación Ctrl + Shift + k) de todas formas el comando aparece en la historia de comandos (arriba-derecha). Si no lo encuentra, use la lupa o buscador, que aparece en la pestaña History y escriba `setwd`, para filtrar la historia. Si selecciona con el ratón dicho comando, con el botón "To Source" puede enviar este comando al editor de texto; recuerde ubicarlo al principio del mismo, en la línea 1. Y recuerde que tampoco puede usarse un camino relativo aquí (más adelante se explica por qué).

De aquí en más agarrar algún ejercicio del repartido 1 y hacerlo paso a paso

### Ejemplo: polinomios

Como se traduce la ecuación de un polinomio a R. Cuál es la gracia de sustituir x por un valor y viceversa.

### Resolviendo un ejercicio de repartido

### X Soluciones genéricas

La filosofía nuestra es de que el codigo sea reusable/reciclable.

### Usando la función evaluar

Cargando el archivo.

Notas mayores a 100% (ejercicios extras).

### El archivo datos

Cómo saber si está actualizado. Cómo bajarlo. Qué hacer si windows lo transforma en datos.txt (nada, al cargar evaluar.R se el nombre se modifica a datos a secas). 

### Errores.

A no tener miedo de cometerlos. Hasta los más experimentados vivimos cometiendo errores, incluso los más tontos (pero por suerte, con menos frecuencia). No es cometer o no errores lo que te hace un buen programador. Un buen progamador se define por su capacidad de anticiparse a lo que necesita y a cómo obtenerlo; es quien puede visualizar cómo interactúan las distintas piezas del sistema que él mismo está diseñando. Es en gran medida, un diseñador/arquitecto.

### Entregar un repartido con retraso:

X días, Y horas de retraso ---> penalización = (X + 1) * 5 (siempre que Y > 0).









